version: "3.9"

services:
  music-api:
    image: kkkk098/music-app:api-latest
    container_name: music-api
    ports:
      - "8000:8000"
    restart: always
    environment:
      WEIGHTS_PATH: /models/model.pth
    volumes:
      - model-data:/models
    command: >
      sh -c "
      if [ ! -f /models/model.pth ]; then
        curl -L -o /models/model.pth https://github.com/Kkkk098/music_bot_cloud_computing/releases/download/v1.0/best_model_heavy_m192_h256_gru256x2.pth;
      fi &&
      uvicorn api:app --host 0.0.0.0 --port 8000
      "      

  music-bot:
    image: kkkk098/music-app:bot-latest
    container_name: music-bot
    depends_on:
      - music-api
    restart: always
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      API_URL: http://music-api:8000/predict_segmented

volumes:
  model-data:
